version: '3.7'
services:
  licensingService:
    image: license:0.0.1
    ports:
      - '8080:8080'
    environment:
      - 'SPRING_PROFILES_ACTIVE=dev'
    networks:
      backend:
        aliases:
          - 'licenseservice'
networks:
  backend:
    driver: bridge